### ISSUE TITLE
Produce a static binary

### ISSUE THREAD

**Issue by srid** [juspay/nix-health#13]
There are situations where it may not be realistic to ask the user to `nix run` this program, viz.: missing `cache.nixos.org` (wherein the whole world compiles).

Let's provide a static binary for macOS to begin with.

**Comment by shivaraj-bh** [comment]
It is easy on linux:

```sh
nix build github:shivaraj-bh/nix-health/static-linux
ldd ./result/bin/nix-health
```

But in macOS, last I remember you cannot produce a fully static binary, the system libraries are always going to remain dynamic.

**Comment by srid** [comment]
@shivaraj-bh Could you open a PR for your branch? Let's get it into `main` even if it is only for Linux.

> the system libraries are always going to remain dynamic.

Which is fine, as long as it generally works on current macs. We can always provide both packages in the flake.

**Comment by shivaraj-bh** [comment]
https://github.com/juspay/nix-health/pull/23

^ for linux static executable

**Comment by srid** [comment]
https://github.com/juspay/omnix/pull/158
