### ISSUE TITLE
Use `tracing` crate for `nix-health`’s output?

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/nix-health#27]
This change would provide fine-grained control over the verbosity of the `nix-health` output

**Comment by shivaraj-bh** [comment]
Additionally, downstream packages like `nixci` can use this to control the [stream that the output is printed on](https://github.com/srid/nixci/blob/141b295eb374e8a27f8c2bb4556cad1fb27a7f7b/src/logging.rs#L44).

**Comment by srid** [comment]
Yes, that'd be good to do. How well does it operate with colours/ emojis?
